@startuml

abstract class ISrsHttpHandler

ISrsHttpHandler <|-- SrsLiveStream
ISrsHttpHandler o.. SrsHttpMuxEntry

SrsLiveStream o.. SrsSource

SrsHttpMuxEntry o-- ISrsHttpHandler

SrsHttpServeMux o-- SrsHttpMuxEntry

SrsLiveEntry o-- SrsLiveStream
SrsLiveEntry o.. SrsSource

SrsHttpStreamServer o-- SrsHttpServeMux
SrsHttpStreamServer o-- SrsLiveEntry
SrsHttpStreamServer o.. SrsServer

SrsHttpServer o-- SrsHttpStreamServer
SrsHttpServer o.. SrsServer

SrsResourceManager o-- SrsHttpConn

SrsHttpConn o-- SrsHttpCorsMux
SrsHttpConn o.. ISrsHttpServeMux

SrsHttpCorsMux o.. ISrsHttpServeMux

ISrsHttpServeMux <|-- SrsHttpServer

SrsServer o-- SrsHttpServer
SrsServer o-- SrsResourceManager

SrsSource o.. SrsServer
SrsSource o-- SrsPlayEdge
SrsSource o-- SrsConsumer

SrsLiveSourceManager o-- SrsSource

SrsConsumer o.. SrsSource

SrsEdgeIngester o.. SrsSource

SrsPlayEdge o-- SrsEdgeIngester

@enduml